config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :brands
  resources :fabrics
  resources :sizes
  resources :colors
  resources :images
  resources :galleries
  resources :products
  resources :product_codes
  resources :orders
  resources :order_items
  resources :payment_types
  resources :order_statuses

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'catalog' => 'categories#catalog', :as => 'catalog'
  post 'catalog' => 'categories#catalog', :as => 'catalog_post'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]
  match 'remote_image_add', to: 'image#create_from_gallery', via: [:post]
  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup
  devise_scope :users do
    get "sign_out", to: 'devise/sessions#destroy'
    delete "sign_out", to: 'devise/sessions#destroy'
  end

  resources :users

  resources :categories do
    member do
      get :session_update
    end
  end

  resources :colors do
    member do
      get :gid
    end
  end

  resources :fabrics do
    member do
      get :image
    end
  end

  resources :galleries do
    member do
      get  :gallery
      post :product
    end
  end

  resources :products do
    member do
      post :picture
      get :get_catalog
      get :show_product
      get :view
      get :show_full
      get :show_mode
      get :get_deffered
      get :remove_deffered
      get :privatpolicy
    end
  end

  resources :product_codes do
    member do
      get :get_free_gallery
      get :set_gallery
    end
  end

  resources :order_items do
    member do
      get :create_box
      patch :add_order
      patch :add_order_box
    end
  end

  resources :orders do
    member do
      get :newbox
      get :last
      get :history
      patch :add_attr
      get :approve
    end
  end

  root 'static_pages#home'

end

app/models/fabric.rb
# == Schema Information
#
# Table name: fabrics
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  composition :string(255)
#  attachement :string(255)
#  image_id    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer
#

class Fabric < ActiveRecord::Base
  attachment :image, content_type: ["image/jpeg", "image/png", "image/gif"]
  has_many :galleries
  belongs_to :category
end

app/controllers/fabrics_controller.rb
# == Schema Information
#
# Table name: fabrics
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  composition :string(255)
#  attachement :string(255)
#  image_id    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer
#

class FabricsController < ApplicationController
  before_action :require_admin
  def index
    @fabrics = Fabric.where("fabrics.category_id IS NULL OR fabrics.category_id = '#{session['category']}'").order("fabrics.created_at DESC")
  end

  def show
    @fabric = Fabric.find(params[:id])
  end

  def image
    @fabric = Fabric.find(params[:id])
    render :partial => 'image'
  end

  def new
    @fabric = Fabric.new
  end

  def create
    @fabric = Fabric.new(fabric_params)
    !@fabric.save && (redirect_to new_fabrics_path)
    redirect_to fabrics_path
  end

  def edit
    @fabric = Fabric.find(params[:id])
  end

  def update
    @fabric = Fabric.find(params[:id])
    !@fabric.update_attributes(fabric_params) && (redirect_to edit_fabrics_path)
    redirect_to @fabric
  end

  def destroy
    @fabric = Fabric.find(params[:id])
    @fabric.destroy
    redirect_to fabrics_path
  end

  private

  def fabric_params
    params.require(:fabric).permit(:name, :description, :composition, :image, :category_id)
  end
end

app/helpers/fabrics_helper.rb
# == Schema Information
#
# Table name: fabrics
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  composition :string(255)
#  attachement :string(255)
#  image_id    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

module FabricsHelper
end

app/views/fabrics/_form.html.haml
= form_for(@fabric) do |f|
  - if @fabric.errors.any?
    .alert.alert-error
      %b
        = pluralize(@fabric.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @fabric.errors.full_messages.each do |msg|
          %li= msg
  = attachment_image_tag(@fabric, :image, :fill, 300, 300, fallback: "default300x300.png", class: 'image_uploaded')
  %table.table-striped.table-bordered.table-condensed.table-user-form{:role => "grid"}
    %tr
      %td{:scope => "row"}= f.label :name
      %td= f.text_field :name, class: "name_field"
    %tr
      %td{:scope => "row"}= f.label :description
      %td= f.text_area :description, class: "name_field"
    %tr
      %td{:scope => "row"}= f.label :category
      %td= f.collection_select :category_id, Category.all, :id, :name_ua, {:selected => session["category"]}
    %tr
      %td{:scope => "row"}= f.label :composition
      %td= f.text_field :composition, class: "name_field"
    %tr
      %td{:scope => "row"}= f.label :image
      %td= f.attachment_field :image, direct: true, presigned: true, class: 'file_uploader'
    %tr
      %td= bootstrap_icon_link_to t(:_cansel), fabrics_path, 'glyphicon glyphicon-time icon-white', :class => "button btn btn-warning"
      %td= f.submit :class => "button btn btn-success"

app/views/fabrics/_image.html.haml
= attachment_image_tag(@fabric, :image, :fill, 300, 300, fallback: "default300x300.png")

app/views/fabrics/edit.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.fabric.edit') + @fabric.name
      = render 'form'

app/views/fabrics/index.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.fabric.index')
      %table.table.table-striped.table-bordered.table-condensed{:role => "grid"}
        %thead
          %tr
            %th{:scope => "column"}
              = t('admins.headers.name_i')
            %th{:scope => "column"}
              = t('admins.headers.description')
            %th{:scope => "column"}
              = t('admins.headers.created_at')
            %th{:scope => "column"}
              = t('admins.headers.composition')
            %th{:scope => "column"}
              = t('admins.headers.picture')
            %th{:scope => "column"}
        %tbody
          - @fabrics.each do |f|
            %tr
              %td= f.name
              %td= f.description
              %td= f.created_at
              %td= f.composition
              %td= attachment_image_tag(f, :image, :fill, 300, 300, fallback: "default300x300.png")
              %td
                = bootstrap_icon_link_to t(:_show), f, "glyphicon glyphicon-th icon-white", method: :get, :class => "button btn btn-small btn-primary"
                = bootstrap_icon_link_to t(:_edit), edit_fabric_path(f), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
                = bootstrap_icon_link_to t(:_delete), f, "glyphicon glyphicon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "button btn btn-small btn-danger"
                %br
                %span
                  in:
                %br
                = f.category_id && Category.find(f.category_id).name_ua

app/views/fabrics/new.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.fabric.new')
      = render 'form'

app/views/fabrics/show.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.fabric.profile') + @fabric.name
      %table.table.table-striped.table-bordered.table-condensed.table-user-profile{:role => "grid"}
        %tr
          %td{:scope => "row"} Name
          %td= @fabric.name
        %tr
          %td{:scope => "row"} Description
          %td= @fabric.description
        %tr
          %td{:scope => "row"} Category
          %td= @fabric.category_id && Category.find(@fabric.category_id).name_ua
        %tr
          %td{:scope => "row"} Composition
          %td= @fabric.composition
        %tr
          %td{:scope => "row"} Parent
          %td= attachment_image_tag(@fabric, :image, :fill, 300, 300, fallback: "default300x300.png")
        %tr
          %td{:scope => "row"}
          %td
            = bootstrap_icon_link_to t(:_edit), edit_fabric_path(@fabric), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
            - if current_user.is_admin
              = bootstrap_icon_link_to t(:_delete), @fabric, "glyphicon glyphicon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "button btn btn-small btn-danger"