config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :brands
  resources :fabrics
  resources :sizes
  resources :colors
  resources :images
  resources :galleries
  resources :products
  resources :product_codes
  resources :orders
  resources :order_items
  resources :payment_types
  resources :order_statuses

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'catalog' => 'categories#catalog', :as => 'catalog'
  post 'catalog' => 'categories#catalog', :as => 'catalog_post'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]
  match 'remote_image_add', to: 'image#create_from_gallery', via: [:post]
  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup
  devise_scope :users do
    get "sign_out", to: 'devise/sessions#destroy'
    delete "sign_out", to: 'devise/sessions#destroy'
  end

  resources :users

  resources :categories do
    member do
      get :session_update
    end
  end

  resources :colors do
    member do
      get :gid
    end
  end

  resources :fabrics do
    member do
      get :image
    end
  end

  resources :galleries do
    member do
      get  :gallery
      post :product
    end
  end

  resources :products do
    member do
      post :picture
      get :get_catalog
      get :show_product
      get :view
      get :show_full
      get :show_mode
      get :get_deffered
      get :remove_deffered
      get :privatpolicy
    end
  end

  resources :product_codes do
    member do
      get :get_free_gallery
      get :set_gallery
    end
  end

  resources :order_items do
    member do
      get :create_box
      patch :add_order
      patch :add_order_box
    end
  end

  resources :orders do
    member do
      get :newbox
      get :last
      get :history
      patch :add_attr
      get :approve
    end
  end

  root 'static_pages#home'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  show        :boolean
#  amount_min  :integer
#  amount_max  :integer
#  price_min   :integer
#  price_max   :integer
#  cut_type    :string(255)
#  collar_type :string(255)
#  sleeve_type :string(255)
#  cuff_type   :string(255)
#  style_type  :string(255)
#  brand_id    :integer
#  category_id :integer
#  picture_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Product < ActiveRecord::Base
  include ApplicationHelper
  acts_as_opengraph
  has_many :galleries
  has_many :images, through: :galleries
  has_many :colors, through: :galleries
  has_many :fabrics, through: :galleries
  has_one :picture, class_name: "Image", foreign_key: "picture_id"
  belongs_to :category
  belongs_to :brand
  has_and_belongs_to_many :sizes

  def opengraph_title
    self.brand.name + ' $' + self.price_max.to_s + '  ' + self.sizes.map {|s| s.sign}.join(':')
  end
  def opengraph_url
    "http://" + Thread.current[:request] + "/product/" + self.id.to_s + "/view?locale="+I18n.locale.to_s
  end
end

app/controllers/products_controller.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  show        :boolean
#  amount_min  :integer
#  amount_max  :integer
#  price_min   :integer
#  price_max   :integer
#  cut_type    :string(255)
#  collar_type :string(255)
#  sleeve_type :string(255)
#  cuff_type   :string(255)
#  style_type  :string(255)
#  brand_id    :integer
#  category_id :integer
#  picture_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class ProductsController < ApplicationController
  before_action :require_admin, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  def index
    @products = Product.where("products.category_id IS NULL OR products.category_id = '#{session['category']}'").order('products.created_at ASC')
  end

  def show
    @product = Product.find(params[:id])
    @galleries = Gallery.where("galleries.product_id = '#{params[:id]}'")
    ##!@galleries.blank? && (@fabric = Fabric.find(@galleries.first.fabric_id))
  end

  def view
    @product = Product.find(params[:id])
    @category = Category.find(@product.category_id)
    @galleries = Gallery.where("galleries.product_id = '#{params[:id]}'")
    ##!@galleries.blank? && (@fabric = Fabric.find(@galleries.first.fabric_id))
    @orders = Order.uncached do
      Order.where(:temporary => session['temporary'], :closed => false)
    end
    !@orders.blank? && (@order = @orders.last)
    @amounts = []
    @product_codes_ids = ProductCode.where(product_id: @product.id).map {|p| p.id}
    session['temporary'] && OrderItem.all.where(temporary: session['temporary'], :product_code_id => @product_codes_ids).each do |oi|
      @amounts[oi.product_code_id] = oi.amount
    end
    session['deffered'].delete_if {|d| d == @product.id}
    session['deffered'] << @product.id
    session['deffered'].uniq.compact
  end

  def show_mode
    session['view'] = params[:product][:view]
    respond_to do |format|
      format.js
    end
  end

  def show_product
    @product = Product.find(params[:id])
    @galleries = Gallery.where("galleries.product_id = '#{params[:id]}'")
    ##!@galleries.blank? && (@fabric = Fabric.find(@galleries.first.fabric_id))
    @orders = Order.uncached do
      Order.where(:temporary => session['temporary'], :closed => false)
    end
    @orders.blank? && (redirect_to root_path)
    !@orders.blank? && (@order = @orders.last)
    @amounts = []
    @product_codes_ids = ProductCode.where(product_id: @product.id).map {|p| p.id}
    @temper = session['temporary']
    OrderItem.all.where(temporary: @temper, :product_code_id => @product_codes_ids).each do |oi|
      @amounts[oi.product_code_id] = oi.amount
    end
    @locale = (!params[:locale].blank? && ('?locale=' + params[:locale]))||''
    session['deffered'].delete_if {|d| d == @product.id}
    session['deffered'] << @product.id
    session['deffered'].uniq.compact
    render :partial => 'prod'
  end

  def show_full
    @product = Product.find(params[:id])
    @galleries = Gallery.where("galleries.product_id = '#{params[:id]}'")
    ##!@galleries.blank? && (@fabric = Fabric.find(@galleries.first.fabric_id))
    @height = params[:height].to_i + 200
    @width = @height * 3 / 4
    render :partial => 'full'
  end

  def get_deffered
    if( defined? params[:product][:shift])
      params[:product][:shift] == 'left' && @shift = session['deffered'].last
      params[:product][:shift] == 'right' && @shift = session['deffered'].first
      session['deffered'].delete_if {|d| d == @shift}
      params[:product][:shift] == 'left' && session['deffered'].unshift(@shift)
      params[:product][:shift] == 'right' && session['deffered'] << @shift
      session['deffered'].uniq.compact
    end
    render :partial => 'deffered'
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @sizes_ids = params[:product][:size_ids].reject { |s| s.empty? }
    @sizes = Size.where("sizes.id IN (#{@sizes_ids.join(',')})")
    !@product.save && (redirect_to new_product_path)
    redirect_to edit_product_path(@product), :notice => 'please, select gallery!'
  end

  def edit
    @product = Product.find(params[:id])
    @galleries = Gallery.where("galleries.product_id = '#{params[:id]}'")
    ##!@galleries.blank? && (@fabric = Fabric.find(@galleries.first.fabric_id))
    @color_ids = @galleries.map { |g| g.color_id}
    !@color_ids.blank? && (@colors = Color.where("colors.id IN (#{@color_ids.join(',')})"))
    @galleries_for_add = Gallery.where("galleries.category_id = '#{session['category']}'")
    !@galleries.blank? && (@galleries_for_add -= @galleries)
    session['product_id'] = @product.id
  end

  def update
    @product = Product.find(params[:id])
    @sizes_ids = params[:product][:size_ids].reject { |s| s.empty? }
    @sizes = Size.where("sizes.id IN (#{@sizes_ids.join(',')})")
    @product.sizes = @sizes
    !@product.update(product_params) && (redirect_to edit_product_path)
    redirect_to @product
  end

  def picture
    @product = Product.find(params[:id])
    !@product.permit(:picture_id).update(params[:picture_id]) && (redirect_to edit_product_path)
    redirect_to edit_product_path( session['product_id'])
  end

  def get_catalog
    @products = Product.where("products.category_id = '#{session['category']}'").order('products.updated_at DESC')
    @width = params[:width].to_i
    @size = 225
    @width < 768 && @size = 200
    @width < 478 && @size = 160
    @pointX = @width/2 -122
    @width < 478 && @pointX = @width -200
    @point = @pointY = @pointX
    @top = 230
    @step = @size * 1.1
    @topstep = 12
    @zindex = 100000
    @aspect = 0
    @pleft = 0
    @pright = 0
    @k = 1
    @hash = []
    @pos = 'start'
    @products.each do |p|
      if(@pos != 'start')
        if(@pos == 'left')
          @pos = 'right'
          @point = @pointX -= @step
          @width > 768 && @point < 30 && @point = 30
          @aspect = -@pright +=1
          @top -= @topstep
          @top < 120 && @top = 120
          @zindex -= 1
        else
          @pos = 'left'
          @point = @pointY += @step
          @width > 768 && @point > @width * 0.78 && @point = @width * 0.78
          @aspect = @pleft += 1
          @step -= @step/(2*@k)
          @k++
          @topstep += 10 + (@topstep /2)
        end
      else @pos = 'left'
      end
      @hash[p.id] = {'point' => @point, 'top' => @top, 'zindex' => @zindex, 'aspect' => @aspect}
    end
    @locale = (!params[:locale].blank? && ('?locale=' + params[:locale]))||''
    session['view'] == 'grid' &&(render :partial => 'cat2')
    session['view'] == 'showcase' && (render :partial => 'cat1')
    (session['view'] != 'showcase' && session['view'] != 'grid') && (redirect_to root_path)
  end

  def remove_deffered
    session['deffered'] = session['deffered'].delete_if {|d| d == params[:product][:deffered].to_i}
    session['deffered'] = session['deffered'].compact
    render :partial => 'deffered'
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def privatpolicy
    redirect_to privatpolicy_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand_id, :category_id, :description, :picture_id,
                                    :price_min, :price_max, :amount_min, :amount_max, {size_ids:[]},
                                    :cut_type, :collar_type, :sleeve_type, :cuff_type, :style_type,
                                    :deffered, :shift, :view)
  end
end

app/helpers/products_helper.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  show        :boolean
#  amount_min  :integer
#  amount_max  :integer
#  price_min   :integer
#  price_max   :integer
#  cut_type    :string(255)
#  collar_type :string(255)
#  sleeve_type :string(255)
#  cuff_type   :string(255)
#  style_type  :string(255)
#  brand_id    :integer
#  category_id :integer
#  picture_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

module ProductsHelper
end

app/views/products/_deffered.html.haml
- c = session['deffered'].compact
- c.each do |d|
  - p = Product.find(d)
  - if !p.blank?
    .prod_cel_deffered.wow.lightSpeedIn{'data-id' => "prod_cel#{d}", 'data-wow-duration' => '100ms', 'data-wow-delay' => '100ms'}
      %table.table-condensed.table-catalog-face{:role => "grid"}
        %tr
          %td
            %a{href: "#{view_product_path(p)}", class: "btn-product cat-image-action", 'data-id' => "prod_cel#{d}"}
              = attachment_image_tag((p.picture_id && Image.find(p.picture_id)) || Image.new, :file, :fill, 120, 160, fallback: "default120x160.png", class: 'image_uploaded')
        %tr
          %td
            %table.table-condensed.table-catalog-face-label{:role => "grid"}
              %tr
                %td.cat-price
                  %span.cat-price
                    = '$'+p.price_max.to_s
                %td.close
                  %a{href: '#close', 'data-id' => "#{d}"}
                    %i.glyphicon.glyphicon-remove.icon-red
              %tr
                %td
                  %a.btn.btn-start.btn-more.btn-product.animated.scroll.topbutton.fadeInUpBig{ href: "#{view_product_path(p)}", id:"#prod#{d}", 'data-id' => "prod_cel#{d}", class: "btn-more-#{d}"}
                    =t(:_furthermore)
.nav-deff
  .deff-spacer.wow.lightSpeedIn{'data-wow-duration' => '100ms', 'data-wow-delay' => '100ms'}
  %a.btn.animated.scroll.btn-nav-deff.btn-nav-deff-left.lightSpeedIn{ href: "#"}
    %i.glyphicon.glyphicon-chevron-left
    %i.glyphicon.glyphicon-chevron-left
    %i.glyphicon.glyphicon-chevron-left
  %a.btn.animated.scroll.btn-nav-deff.btn-nav-deff-right.lightSpeedIn{ href: "#"}
    %i.glyphicon.glyphicon-chevron-right
    %i.glyphicon.glyphicon-chevron-right
    %i.glyphicon.glyphicon-chevron-right

app/views/products/_form.html.haml
= form_for(@product) do |f|
  - if @product.errors.any?
    .alert.alert-error
      %b
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  %table.table-striped.table-bordered.table-condensed.table-product-picture{:role => "grid"}
    %tr
      %td= attachment_image_tag((@product.picture_id && Image.find(@product.picture_id)) || Image.new, :file, :fill, 300, 400, fallback: "default300x400.png", class: 'image_uploaded')
  %table.table-striped.table-bordered.table-condensed.table-product-form{:role => "grid"}
    %tr
      %td{:scope => "row"}
        = f.label :name
        = f.hidden_field :id
        = f.hidden_field :picture_id
      %td.order_field= f.text_field :name, class: 'text_input'
    %tr.brand_image_insert
      %td{:scope => "row"}= f.label :brand
      %td= f.collection_select :brand_id, Brand.all, :id, :name, {:selected => @product.brand_id}
    %tr
      %td{:scope => "row"}= f.label :category
      %td= f.collection_select :category_id, Category.all.where('categories.parent_id IS NOT NULL'), :id, :name_ua, {:selected => @product.category_id}
    %tr.product_description
      %td{:scope => "row"}= f.label :description
      %td= f.text_area :description, class: 'text_input'
    %tr
      %td{:scope => "row"}= f.label t('admins.headers.price')
      %td.number_field= f.number_field :price_max
    %tr
      %td{:scope => "row"}= f.label  t('admins.headers.amount')
      %td.number_fiel= f.number_field :amount_max
    %tr
      %td{:scope => "row"}= f.label :sizes
      %td= f.collection_check_boxes(:size_ids, Size.all, :id, :sign)
    %tr
      %td= bootstrap_icon_link_to t(:_cansel), products_path, 'glyphicon glyphicon-time icon-white', :class => "button btn btn-warning"
      %td= f.submit :class => "button btn btn-success"
  %table.table-striped.table-bordered.table-condensed.table-product-picture{:role => "grid"}
    %tr
      %td= attachment_image_tag((@fabric || Fabric.new), :image, :fill, 300, 300, fallback: "default300x300.png", class: 'image_uploaded')
    - if(@fabric)
      %tr
        %input{type: 'hidden', id: 'fabric_id', name: 'fabric_id', value: "#{@fabric.id}"}
        %td=@fabric.name
      %tr
        %td=@fabric.description
      %tr
        %td=@fabric.composition
  %table.table-striped.table-bordered.table-condensed.table-product-char-form{:role => "grid"}
    - !@colors.blank? && @colors.each do |c|
      %tr
        %td{:scope => "row"}= f.label  t('activerecord.models.color')
        %td.order_field
          = c.name
          .color_square{style: "background-color: #{c.color_gid}"}
    %tr
      %td{:scope => "row"}= f.label :cut_type
      %td.order_field= f.text_field :cut_type, class: "text_input"
    %tr
      %td{:scope => "row"}= f.label :collar_type
      %td.order_field= f.text_field :collar_type, class: "text_input"
    %tr
      %td{:scope => "row"}= f.label :sleeve_type
      %td.order_field= f.text_field :sleeve_type, class: "text_input"
    %tr
      %td{:scope => "row"}= f.label :cuff_type
      %td.order_field= f.text_field :cuff_type, class: "text_input"
    %tr
      %td{:scope => "row"}= f.label :style_type
      %td.order_field= f.text_field :style_type, class: "text_input"
  - !@galleries.blank? && @galleries.each do |b|
    - b.images.each do |i|
      %table.table-striped.table-bordered.table-condensed.table-product-picture-set{:role => "grid"}
        %tr
          %td= attachment_image_tag(i || Image.new, :file, :fill, 300, 400, fallback: "default300x400.png", class: 'image_uploaded')
        %tr
          %td
            %input{type: 'hidden', id: 'image_id', name: 'image_id', value: "#{i.id}"}
            = bootstrap_icon_link_to t('admins.headers.set_as_primary'), '#', "glyphicon glyphicon-check icon-white", :class => "button btn btn-small btn-primary btn-picture-set"
  %table.table-striped.table-bordered.table-condensed.table-product-gallery-form{:role => "grid"}
    - !@galleries.blank? && @galleries.each do |b|
      %tr
        %td= b.name
        %td= b.description
        %td= b.images.count
        %td
          %input{type: 'hidden', id: 'gallery_id', name: 'gallery_id', value: "#{b.id}"}
          = bootstrap_icon_link_to t(:_show), b, "glyphicon glyphicon-book icon-white", method: :get, :class => "button btn btn-small btn-primary"
          = bootstrap_icon_link_to t(:_edit), edit_gallery_path(b), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
          = bootstrap_icon_link_to t('admins.headers.remove_gallery'),"#", "glyphicon glyphicon-trash icon-white", :class => "button btn btn-small btn-warning btn-gallery-remove"
    %tr
      %td
        = bootstrap_icon_link_to t('admins.headers.add_gallery'), '#', "glyphicon glyphicon-plus icon-white", method: :get, :class => "button btn btn-small btn-primary"
      %td.select_gallery
        - if(!@product.id.blank?)
          = collection_select @product, 'gallery_id', @galleries_for_add, :id, :name, include_blank: t('admins.headers.select_gallery')
  .gallery_insert_box

app/views/products/edit.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.product.edit') + @product.name
      = render 'form'
:javascript
  admit_product();

app/views/products/index.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.product.index')
      %table.table.table-striped.table-bordered.table-condensed{:role => "grid"}
        %thead
          %tr
            %th{:scope => "column"}
              = t('activerecord.attributes.product.name')
            %th{:scope => "column"}
              = t('activerecord.attributes.product.brand')
            %th{:scope => "column"}
              = t('activerecord.attributes.product.picture')
            %th{:scope => "column"}
        %tbody
          - @products.each do |b|
            %tr
              %td= b.name
              %td= attachment_image_tag(b.brand || Brand.new, :image, :fill, 300, 100, fallback: "default300x100.png", class: 'image_uploaded')
              %td= attachment_image_tag((b.picture_id && Image.find(b.picture_id)) || Image.new, :file, :fill, 150, 200, fallback: "default300x100.png", class: 'image_uploaded')
              %td
                = bootstrap_icon_link_to t(:_show), b, "glyphicon glyphicon-book icon-white", method: :get, :class => "button btn btn-small btn-primary"
                = bootstrap_icon_link_to t(:_edit), edit_product_path(b), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
                = bootstrap_icon_link_to t(:_delete), b, "glyphicon glyphicon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "button btn btn-small btn-danger"

app/views/products/new.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.product.new')
      = render 'form'
:javascript
  admit_product();

app/views/products/show.html.haml
#adminpanel
  = render 'admin_panel_controlls'
  = show_flash
  .tab-content
    %fieldset
      %legend
        = t('activerecord.attributes.product.profile') + @product.name
      %table.table-striped.table-bordered.table-condensed.table-product-picture{:role => "grid"}
        %tr
          %td= attachment_image_tag((@product.picture_id && Image.find(@product.picture_id)) || Image.new, :file, :fill, 300, 400, fallback: "default300x400.png", class: 'image_uploaded')
      %table.table-striped.table-bordered.table-condensed.table-product-form{:role => "grid"}
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.name')
          %td.name_field= @product.name
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.brand')
          %td.name_field
            - if(@product.brand_id)
              - b = Brand.find(@product.brand_id)
              = attachment_image_tag(b, :image, :fill, 300, 100, fallback: "default300x100.png")
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.category')
          %td.name_field= @product.category_id && Category.find(@product.category_id).name_ua
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.description')
          %td.name_field= @product.description
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.price')
          %td.name_field= @product.price_max && (@product.price_max.to_s + '$')
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.amount')
          %td.name_field= @product.amount_max && (@product.amount_max.to_s)
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.sizes')
          %td.name_field
            %table.table-striped.table-bordered.table-condensed.table-size-show{:role => "grid"}
              %tr
                - @product.sizes.each do |s|
                  %td
                    = s.sign
        %tr
          %td{:scope => "row"}
          %td.name_field
            = bootstrap_icon_link_to t(:_edit), edit_product_path(@product), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
            - if current_user.is_admin
              = bootstrap_icon_link_to t(:_delete), @product, "glyphicon glyphicon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "button btn btn-small btn-danger"
      %table.table-striped.table-bordered.table-condensed.table-product-char-form{:role => "grid"}
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.cut_type')
          %td.name_field= @product.cut_type
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.collar_type')
          %td.name_field= @product.collar_type
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.sleeve_type')
          %td.name_field= @product.sleeve_type
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.cuff_type')
          %td.name_field= @product.cuff_type
        %tr
          %td{:scope => "row"}
            = t('activerecord.attributes.product.style_type')
          %td.name_field= @product.style_type
:javascript
  admit_product();

app/views/products/show_mode.js.erb
$('#navpanel0 .nav-catalog').html("<%= escape_javascript(render "nav1", :formats => [:html]) %>");
show_catalog();

app/views/products/view.html.haml
= content_for :opengraph_meta_tags, opengraph_meta_tags_for(@product)
= content_for :custom_meta_tags do
  %link{rel: "canonical", href: "#{request.original_url}"}
  %meta{property: "og:image", content: "#{'http://' + request.host_with_port + attachment_url((@product.picture_id && Image.find(@product.picture_id)) || Image.new, :file, :fill, 300, 400, fallback: "default300x400.png")}"}
  %meta{property: "og:image:type", content: "image/jpeg"}
  %meta{property: "og:image:width", content: "300"}
  %meta{property: "og:image:height", content: "400"}
  - keywords = ['сорочка', 'shirt', 'рубашка', 'сорочки', 'shirts', 'рубашки', 'гуртом', 'wholesale', 'оптом']
  - keywords << ['turkey', 'турция', 'турція', 'турецкие', 'турецькі', 'turkish']
  - @category || @category = Category.find(session['category'])
  - keywords << @category.name_ua.split(' ')
  - keywords << @category.name_en.split(' ')
  - keywords << @category.name_ru.split(' ')
  - keywords << Brand.find(@product.brand_id).name
  - keywords << @product.sizes.map {|s| s.sign}
  - keywords << @galleries.map {|g| Color.find(g.color_id).name.split(' ')}
  %meta{name: "keywords", content: "#{keywords.join(', ')}"}
.top_box.clearfix
%section#navpanel.topwhite
  .nav0-tabs.nav.nav-tabs
    .flash.wow.lightSpeedIn{data: {tabs: "tabs"}, 'data-wow-duration' => '1000ms', 'data-wow-delay' => '200ms'}
  .deffered-nav
    = render partial: 'deffered'
%section#product
  = render partial: 'prod'
:javascript
  $('.main-nav li').removeClass('active');
  $('.main-nav li.btn-nav-catalog').addClass('active');
  get_gallery();
  zoom_action($('#product-image'));
  add_action($('.product-add'));
  renew_hash();
  remove_deffered();
  deffered_view();
  deffered_shift();
  get_full();